"""Generate Vector's processing pipeline from human-approved parsers (D23).

vector/vector.yaml holds the sources; vector/pipeline.yaml is generated and holds the
routing, one remap per approved parser, and the sink. A line that no parser matches, or
on which its parser fails, goes to the quarantine.
"""

from __future__ import annotations

import json
from pathlib import Path

HEADER = "# GENERATED by `privasoc vector-config` from approved parsers. Do not edit.\n"


def _indent(text: str, n: int) -> str:
    pad = " " * n
    return "\n".join(pad + line if line.strip() else "" for line in text.splitlines())


def _wrap(parser_id: str, vrl: str) -> str:
    """Run the parser on a clean event {message}, then rebuild the envelope."""
    return (
        "ps_raw = string!(.message)\n"
        "ps_src = .privasoc_source\n"
        "ps_ts = .timestamp\n"
        "# Round-trip through JSON so the type checker treats the event as an open object.\n"
        '. = object!(parse_json!(encode_json({"message": ps_raw})))\n'
        f"{vrl.strip()}\n"
        ".event.original = ps_raw\n"
        "ps_ecs = .\n"
        f'. = {{"message": ps_raw, "privasoc_source": ps_src, "timestamp": ps_ts, '
        f'"ecs": ps_ecs, "parser_id": {json.dumps(parser_id)}}}\n'
    )


def render(parsers: list[dict]) -> str:
    """parsers: approved rows with id, source, vrl."""
    lines = [
        HEADER,
        "transforms:",
        "  by_source:",
        "    type: route",
        "    inputs: [tag_source]",
        "    route:",
    ]
    if not parsers:
        lines.append("      _none: 'false'")
    for p in parsers:
        lines.append(
            f"      p_{p['id']}: {json.dumps('.privasoc_source == ' + json.dumps(p['source']))}"
        )
    sink_inputs = ["by_source._unmatched"]
    for p in parsers:
        name = f"parse_{p['id']}"
        lines += [
            f"  {name}:",
            "    type: remap",
            f"    inputs: [by_source.p_{p['id']}]",
            "    drop_on_error: true",
            "    reroute_dropped: true",
            "    source: |",
            _indent(_wrap(p["id"], p["vrl"]), 6),
        ]
        sink_inputs += [name, f"{name}.dropped"]
    lines += [
        "",
        "sinks:",
        "  privasoc:",
        "    type: http",
        f"    inputs: [{', '.join(sink_inputs)}]",
        "    uri: ${PRIVASOC_INGEST_URL:-http://privasoc:8000/ingest}",
        "    method: post",
        "    encoding:",
        "      codec: json",
        "      only_fields: [message, privasoc_source, timestamp, ecs, parser_id]",
        "    framing: { method: newline_delimited }",
        "    auth:",
        "      strategy: bearer",
        "      token: ${PRIVASOC_API_TOKEN}",
        "    batch: { max_events: 500, timeout_secs: 1 }",
        "    request: { retry_attempts: 10 }",
        "",
    ]
    return "\n".join(lines)


def write(parsers: list[dict], vector_dir: Path) -> Path:
    path = vector_dir / "pipeline.yaml"
    path.write_text(render(parsers), encoding="utf-8")
    return path


def validate(vector_bin: str, vector_dir: Path) -> str | None:
    """Run `vector validate` on the directory; return the error text or None."""
    import os
    import subprocess
    import tempfile

    with tempfile.TemporaryDirectory() as d:
        d = Path(d).as_posix()  # forward slashes: safe inside YAML strings on Windows
        env = {
            **os.environ,
            "PRIVASOC_API_TOKEN": "validate",
            "VECTOR_DATA_DIR": d,
            "PRIVASOC_INBOX": d,
        }
        try:
            proc = subprocess.run(  # noqa: S603 - fixed argv
                [
                    vector_bin,
                    "validate",
                    "--skip-healthchecks",
                    "--no-environment",
                    "--config-dir",
                    str(vector_dir),
                ],
                capture_output=True,
                text=True,
                env=env,
                check=False,
            )
        except OSError as exc:  # binary missing or not executable: nothing is deployed
            return f"cannot run {vector_bin}: {exc}"
    return None if proc.returncode == 0 else (proc.stdout + proc.stderr)[-3000:]
